services:
  - type: web
    name: healtho-chatbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate --noinput && gunicorn healtho_backend.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: healtho-chatbot.onrender.com,localhost,127.0.0.1
